import os

POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
EVOEF2_BINARY_PATH = os.getenv("EVOEF2_BINARY_PATH")
DFIRE2_FOLDER_PATH = os.getenv("DFIRE2_FOLDER_PATH")
ROSETTA_BINARY_PATH = os.getenv("ROSETTA_BINARY_PATH")
AGGRESCAN3D_SCRIPT_PATH = os.getenv("AGGRESCAN3D_SCRIPT_PATH")
