import os

POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
EVOEF2_BINARY_PATH = os.getenv("EVOEF2_BINARY_PATH")
DFIRE2_FOLDER_PATH = os.getenv("DFIRE2_FOLDER_PATH")
ROSETTA_BINARY_PATH = os.getenv("ROSETTA_BINARY_PATH")
AGGRESCAN3D_SCRIPT_PATH = os.getenv("AGGRESCAN3D_SCRIPT_PATH")
MAX_RUN_TIME = os.getenv("MAX_RUN_TIME")
HEADLESS_DESTRESS_WORKERS = os.getenv("HEADLESS_DESTRESS_WORKERS")
HEADLESS_DESTRESS_BATCH_SIZE = os.getenv("HEADLESS_DESTRESS_BATCH_SIZE")
