-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module BigStructure.Object exposing (..)


type BiolUnit
    = BiolUnit


type Chain
    = Chain


type CreateDesign
    = CreateDesign


type Design
    = Design


type DesignChain
    = DesignChain


type Pdb
    = Pdb


type State
    = State
