-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module BigStructure.Object.Chain exposing (..)

import BigStructure.InputObject
import BigStructure.Interface
import BigStructure.Object
import BigStructure.Scalar
import BigStructure.ScalarCodecs
import BigStructure.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet BigStructure.ScalarCodecs.Id BigStructure.Object.Chain
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (BigStructure.ScalarCodecs.codecs |> BigStructure.Scalar.unwrapCodecs |> .codecId |> .decoder)


chainLabel : SelectionSet String BigStructure.Object.Chain
chainLabel =
    Object.selectionForField "String" "chainLabel" [] Decode.string


sequence : SelectionSet String BigStructure.Object.Chain
sequence =
    Object.selectionForField "String" "sequence" [] Decode.string


stateId : SelectionSet (Maybe Int) BigStructure.Object.Chain
stateId =
    Object.selectionForField "(Maybe Int)" "stateId" [] (Decode.int |> Decode.nullable)


state : SelectionSet decodesTo BigStructure.Object.State -> SelectionSet (Maybe decodesTo) BigStructure.Object.Chain
state object_ =
    Object.selectionForCompositeField "state" [] object_ (identity >> Decode.nullable)
