-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module BigStructure.Object.Aggrescan3DResults exposing (..)

import BigStructure.InputObject
import BigStructure.Interface
import BigStructure.Object
import BigStructure.Scalar
import BigStructure.ScalarCodecs
import BigStructure.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet BigStructure.ScalarCodecs.Id BigStructure.Object.Aggrescan3DResults
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (BigStructure.ScalarCodecs.codecs |> BigStructure.Scalar.unwrapCodecs |> .codecId |> .decoder)


logInfo : SelectionSet String BigStructure.Object.Aggrescan3DResults
logInfo =
    Object.selectionForField "String" "logInfo" [] Decode.string


errorInfo : SelectionSet String BigStructure.Object.Aggrescan3DResults
errorInfo =
    Object.selectionForField "String" "errorInfo" [] Decode.string


returnCode : SelectionSet Int BigStructure.Object.Aggrescan3DResults
returnCode =
    Object.selectionForField "Int" "returnCode" [] Decode.int


proteinList : SelectionSet (Maybe String) BigStructure.Object.Aggrescan3DResults
proteinList =
    Object.selectionForField "(Maybe String)" "proteinList" [] (Decode.string |> Decode.nullable)


chainList : SelectionSet (Maybe String) BigStructure.Object.Aggrescan3DResults
chainList =
    Object.selectionForField "(Maybe String)" "chainList" [] (Decode.string |> Decode.nullable)


residueNumberList : SelectionSet (Maybe String) BigStructure.Object.Aggrescan3DResults
residueNumberList =
    Object.selectionForField "(Maybe String)" "residueNumberList" [] (Decode.string |> Decode.nullable)


residueNameList : SelectionSet (Maybe String) BigStructure.Object.Aggrescan3DResults
residueNameList =
    Object.selectionForField "(Maybe String)" "residueNameList" [] (Decode.string |> Decode.nullable)


residueScoreList : SelectionSet (Maybe String) BigStructure.Object.Aggrescan3DResults
residueScoreList =
    Object.selectionForField "(Maybe String)" "residueScoreList" [] (Decode.string |> Decode.nullable)


maxValue : SelectionSet (Maybe Float) BigStructure.Object.Aggrescan3DResults
maxValue =
    Object.selectionForField "(Maybe Float)" "maxValue" [] (Decode.float |> Decode.nullable)


avgValue : SelectionSet (Maybe Float) BigStructure.Object.Aggrescan3DResults
avgValue =
    Object.selectionForField "(Maybe Float)" "avgValue" [] (Decode.float |> Decode.nullable)


minValue : SelectionSet (Maybe Float) BigStructure.Object.Aggrescan3DResults
minValue =
    Object.selectionForField "(Maybe Float)" "minValue" [] (Decode.float |> Decode.nullable)


totalValue : SelectionSet (Maybe Float) BigStructure.Object.Aggrescan3DResults
totalValue =
    Object.selectionForField "(Maybe Float)" "totalValue" [] (Decode.float |> Decode.nullable)


stateId : SelectionSet (Maybe Int) BigStructure.Object.Aggrescan3DResults
stateId =
    Object.selectionForField "(Maybe Int)" "stateId" [] (Decode.int |> Decode.nullable)


state :
    SelectionSet decodesTo BigStructure.Object.State
    -> SelectionSet (Maybe decodesTo) BigStructure.Object.Aggrescan3DResults
state object____ =
    Object.selectionForCompositeField "state" [] object____ (identity >> Decode.nullable)
