-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module BigStructure.Object.BiolUnit exposing (..)

import BigStructure.InputObject
import BigStructure.Interface
import BigStructure.Object
import BigStructure.Scalar
import BigStructure.ScalarCodecs
import BigStructure.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet BigStructure.ScalarCodecs.Id BigStructure.Object.BiolUnit
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (BigStructure.ScalarCodecs.codecs |> BigStructure.Scalar.unwrapCodecs |> .codecId |> .decoder)


biolUnitNumber : SelectionSet Int BigStructure.Object.BiolUnit
biolUnitNumber =
    Object.selectionForField "Int" "biolUnitNumber" [] Decode.int


isDepositedPdb : SelectionSet Bool BigStructure.Object.BiolUnit
isDepositedPdb =
    Object.selectionForField "Bool" "isDepositedPdb" [] Decode.bool


isPreferredBiolUnit : SelectionSet Bool BigStructure.Object.BiolUnit
isPreferredBiolUnit =
    Object.selectionForField "Bool" "isPreferredBiolUnit" [] Decode.bool


pdbId : SelectionSet (Maybe Int) BigStructure.Object.BiolUnit
pdbId =
    Object.selectionForField "(Maybe Int)" "pdbId" [] (Decode.int |> Decode.nullable)


pdb :
    SelectionSet decodesTo BigStructure.Object.Pdb
    -> SelectionSet (Maybe decodesTo) BigStructure.Object.BiolUnit
pdb object____ =
    Object.selectionForCompositeField "pdb" [] object____ (identity >> Decode.nullable)


states :
    SelectionSet decodesTo BigStructure.Object.State
    -> SelectionSet (Maybe (List (Maybe decodesTo))) BigStructure.Object.BiolUnit
states object____ =
    Object.selectionForCompositeField "states" [] object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
