-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module BigStructure.Object.BudeFFResults exposing (..)

import BigStructure.InputObject
import BigStructure.Interface
import BigStructure.Object
import BigStructure.Scalar
import BigStructure.ScalarCodecs
import BigStructure.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet BigStructure.ScalarCodecs.Id BigStructure.Object.BudeFFResults
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (BigStructure.ScalarCodecs.codecs |> BigStructure.Scalar.unwrapCodecs |> .codecId |> .decoder)


totalEnergy : SelectionSet (Maybe Float) BigStructure.Object.BudeFFResults
totalEnergy =
    Object.selectionForField "(Maybe Float)" "totalEnergy" [] (Decode.float |> Decode.nullable)


steric : SelectionSet (Maybe Float) BigStructure.Object.BudeFFResults
steric =
    Object.selectionForField "(Maybe Float)" "steric" [] (Decode.float |> Decode.nullable)


desolvation : SelectionSet (Maybe Float) BigStructure.Object.BudeFFResults
desolvation =
    Object.selectionForField "(Maybe Float)" "desolvation" [] (Decode.float |> Decode.nullable)


charge : SelectionSet (Maybe Float) BigStructure.Object.BudeFFResults
charge =
    Object.selectionForField "(Maybe Float)" "charge" [] (Decode.float |> Decode.nullable)


stateId : SelectionSet (Maybe Int) BigStructure.Object.BudeFFResults
stateId =
    Object.selectionForField "(Maybe Int)" "stateId" [] (Decode.int |> Decode.nullable)


state :
    SelectionSet decodesTo BigStructure.Object.State
    -> SelectionSet (Maybe decodesTo) BigStructure.Object.BudeFFResults
state object____ =
    Object.selectionForCompositeField "state" [] object____ (identity >> Decode.nullable)
