-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module BigStructure.Object.EvoEF2Results exposing (..)

import BigStructure.InputObject
import BigStructure.Interface
import BigStructure.Object
import BigStructure.Scalar
import BigStructure.ScalarCodecs
import BigStructure.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet BigStructure.ScalarCodecs.Id BigStructure.Object.EvoEF2Results
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (BigStructure.ScalarCodecs.codecs |> BigStructure.Scalar.unwrapCodecs |> .codecId |> .decoder)


logInfo : SelectionSet String BigStructure.Object.EvoEF2Results
logInfo =
    Object.selectionForField "String" "logInfo" [] Decode.string


errorInfo : SelectionSet String BigStructure.Object.EvoEF2Results
errorInfo =
    Object.selectionForField "String" "errorInfo" [] Decode.string


returnCode : SelectionSet Int BigStructure.Object.EvoEF2Results
returnCode =
    Object.selectionForField "Int" "returnCode" [] Decode.int


referenceAla : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceAla =
    Object.selectionForField "(Maybe Float)" "referenceAla" [] (Decode.float |> Decode.nullable)


referenceCys : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceCys =
    Object.selectionForField "(Maybe Float)" "referenceCys" [] (Decode.float |> Decode.nullable)


referenceAsp : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceAsp =
    Object.selectionForField "(Maybe Float)" "referenceAsp" [] (Decode.float |> Decode.nullable)


referenceGlu : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceGlu =
    Object.selectionForField "(Maybe Float)" "referenceGlu" [] (Decode.float |> Decode.nullable)


referencePhe : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referencePhe =
    Object.selectionForField "(Maybe Float)" "referencePhe" [] (Decode.float |> Decode.nullable)


referenceGly : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceGly =
    Object.selectionForField "(Maybe Float)" "referenceGly" [] (Decode.float |> Decode.nullable)


referenceHis : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceHis =
    Object.selectionForField "(Maybe Float)" "referenceHis" [] (Decode.float |> Decode.nullable)


referenceIle : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceIle =
    Object.selectionForField "(Maybe Float)" "referenceIle" [] (Decode.float |> Decode.nullable)


referenceLys : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceLys =
    Object.selectionForField "(Maybe Float)" "referenceLys" [] (Decode.float |> Decode.nullable)


referenceLeu : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceLeu =
    Object.selectionForField "(Maybe Float)" "referenceLeu" [] (Decode.float |> Decode.nullable)


referenceMet : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceMet =
    Object.selectionForField "(Maybe Float)" "referenceMet" [] (Decode.float |> Decode.nullable)


referenceAsn : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceAsn =
    Object.selectionForField "(Maybe Float)" "referenceAsn" [] (Decode.float |> Decode.nullable)


referencePro : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referencePro =
    Object.selectionForField "(Maybe Float)" "referencePro" [] (Decode.float |> Decode.nullable)


referenceGln : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceGln =
    Object.selectionForField "(Maybe Float)" "referenceGln" [] (Decode.float |> Decode.nullable)


referenceArg : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceArg =
    Object.selectionForField "(Maybe Float)" "referenceArg" [] (Decode.float |> Decode.nullable)


referenceSer : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceSer =
    Object.selectionForField "(Maybe Float)" "referenceSer" [] (Decode.float |> Decode.nullable)


referenceThr : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceThr =
    Object.selectionForField "(Maybe Float)" "referenceThr" [] (Decode.float |> Decode.nullable)


referenceVal : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceVal =
    Object.selectionForField "(Maybe Float)" "referenceVal" [] (Decode.float |> Decode.nullable)


referenceTrp : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceTrp =
    Object.selectionForField "(Maybe Float)" "referenceTrp" [] (Decode.float |> Decode.nullable)


referenceTyr : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
referenceTyr =
    Object.selectionForField "(Maybe Float)" "referenceTyr" [] (Decode.float |> Decode.nullable)


intrarVdwatt : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intrarVdwatt =
    Object.selectionForField "(Maybe Float)" "intrarVdwatt" [] (Decode.float |> Decode.nullable)


intrarVdwrep : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intrarVdwrep =
    Object.selectionForField "(Maybe Float)" "intrarVdwrep" [] (Decode.float |> Decode.nullable)


intrarElectr : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intrarElectr =
    Object.selectionForField "(Maybe Float)" "intrarElectr" [] (Decode.float |> Decode.nullable)


intrarDeslvp : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intrarDeslvp =
    Object.selectionForField "(Maybe Float)" "intrarDeslvp" [] (Decode.float |> Decode.nullable)


intrarDeslvh : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intrarDeslvh =
    Object.selectionForField "(Maybe Float)" "intrarDeslvh" [] (Decode.float |> Decode.nullable)


intrarHbscbbDis : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intrarHbscbbDis =
    Object.selectionForField "(Maybe Float)" "intrarHbscbbDis" [] (Decode.float |> Decode.nullable)


intrarHbscbbThe : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intrarHbscbbThe =
    Object.selectionForField "(Maybe Float)" "intrarHbscbbThe" [] (Decode.float |> Decode.nullable)


intrarHbscbbPhi : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intrarHbscbbPhi =
    Object.selectionForField "(Maybe Float)" "intrarHbscbbPhi" [] (Decode.float |> Decode.nullable)


aapropensity : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
aapropensity =
    Object.selectionForField "(Maybe Float)" "aapropensity" [] (Decode.float |> Decode.nullable)


ramachandran : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
ramachandran =
    Object.selectionForField "(Maybe Float)" "ramachandran" [] (Decode.float |> Decode.nullable)


dunbrack : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
dunbrack =
    Object.selectionForField "(Maybe Float)" "dunbrack" [] (Decode.float |> Decode.nullable)


intersVdwatt : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersVdwatt =
    Object.selectionForField "(Maybe Float)" "intersVdwatt" [] (Decode.float |> Decode.nullable)


intersVdwrep : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersVdwrep =
    Object.selectionForField "(Maybe Float)" "intersVdwrep" [] (Decode.float |> Decode.nullable)


intersElectr : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersElectr =
    Object.selectionForField "(Maybe Float)" "intersElectr" [] (Decode.float |> Decode.nullable)


intersDeslvp : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersDeslvp =
    Object.selectionForField "(Maybe Float)" "intersDeslvp" [] (Decode.float |> Decode.nullable)


intersDeslvh : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersDeslvh =
    Object.selectionForField "(Maybe Float)" "intersDeslvh" [] (Decode.float |> Decode.nullable)


intersSsbond : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersSsbond =
    Object.selectionForField "(Maybe Float)" "intersSsbond" [] (Decode.float |> Decode.nullable)


intersHbbbbbDis : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersHbbbbbDis =
    Object.selectionForField "(Maybe Float)" "intersHbbbbbDis" [] (Decode.float |> Decode.nullable)


intersHbbbbbThe : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersHbbbbbThe =
    Object.selectionForField "(Maybe Float)" "intersHbbbbbThe" [] (Decode.float |> Decode.nullable)


intersHbbbbbPhi : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersHbbbbbPhi =
    Object.selectionForField "(Maybe Float)" "intersHbbbbbPhi" [] (Decode.float |> Decode.nullable)


intersHbscbbDis : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersHbscbbDis =
    Object.selectionForField "(Maybe Float)" "intersHbscbbDis" [] (Decode.float |> Decode.nullable)


intersHbscbbThe : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersHbscbbThe =
    Object.selectionForField "(Maybe Float)" "intersHbscbbThe" [] (Decode.float |> Decode.nullable)


intersHbscbbPhi : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersHbscbbPhi =
    Object.selectionForField "(Maybe Float)" "intersHbscbbPhi" [] (Decode.float |> Decode.nullable)


intersHbscscDis : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersHbscscDis =
    Object.selectionForField "(Maybe Float)" "intersHbscscDis" [] (Decode.float |> Decode.nullable)


intersHbscscThe : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersHbscscThe =
    Object.selectionForField "(Maybe Float)" "intersHbscscThe" [] (Decode.float |> Decode.nullable)


intersHbscscPhi : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersHbscscPhi =
    Object.selectionForField "(Maybe Float)" "intersHbscscPhi" [] (Decode.float |> Decode.nullable)


interdVdwatt : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdVdwatt =
    Object.selectionForField "(Maybe Float)" "interdVdwatt" [] (Decode.float |> Decode.nullable)


interdVdwrep : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdVdwrep =
    Object.selectionForField "(Maybe Float)" "interdVdwrep" [] (Decode.float |> Decode.nullable)


interdElectr : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdElectr =
    Object.selectionForField "(Maybe Float)" "interdElectr" [] (Decode.float |> Decode.nullable)


interdDeslvp : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdDeslvp =
    Object.selectionForField "(Maybe Float)" "interdDeslvp" [] (Decode.float |> Decode.nullable)


interdDeslvh : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdDeslvh =
    Object.selectionForField "(Maybe Float)" "interdDeslvh" [] (Decode.float |> Decode.nullable)


interdSsbond : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdSsbond =
    Object.selectionForField "(Maybe Float)" "interdSsbond" [] (Decode.float |> Decode.nullable)


interdHbbbbbDis : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdHbbbbbDis =
    Object.selectionForField "(Maybe Float)" "interdHbbbbbDis" [] (Decode.float |> Decode.nullable)


interdHbbbbbThe : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdHbbbbbThe =
    Object.selectionForField "(Maybe Float)" "interdHbbbbbThe" [] (Decode.float |> Decode.nullable)


interdHbbbbbPhi : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdHbbbbbPhi =
    Object.selectionForField "(Maybe Float)" "interdHbbbbbPhi" [] (Decode.float |> Decode.nullable)


interdHbscbbDis : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdHbscbbDis =
    Object.selectionForField "(Maybe Float)" "interdHbscbbDis" [] (Decode.float |> Decode.nullable)


interdHbscbbThe : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdHbscbbThe =
    Object.selectionForField "(Maybe Float)" "interdHbscbbThe" [] (Decode.float |> Decode.nullable)


interdHbscbbPhi : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdHbscbbPhi =
    Object.selectionForField "(Maybe Float)" "interdHbscbbPhi" [] (Decode.float |> Decode.nullable)


interdHbscscDis : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdHbscscDis =
    Object.selectionForField "(Maybe Float)" "interdHbscscDis" [] (Decode.float |> Decode.nullable)


interdHbscscThe : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdHbscscThe =
    Object.selectionForField "(Maybe Float)" "interdHbscscThe" [] (Decode.float |> Decode.nullable)


interdHbscscPhi : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdHbscscPhi =
    Object.selectionForField "(Maybe Float)" "interdHbscscPhi" [] (Decode.float |> Decode.nullable)


total : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
total =
    Object.selectionForField "(Maybe Float)" "total" [] (Decode.float |> Decode.nullable)


timeSpent : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
timeSpent =
    Object.selectionForField "(Maybe Float)" "timeSpent" [] (Decode.float |> Decode.nullable)


refTotal : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
refTotal =
    Object.selectionForField "(Maybe Float)" "refTotal" [] (Decode.float |> Decode.nullable)


intrarTotal : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intrarTotal =
    Object.selectionForField "(Maybe Float)" "intrarTotal" [] (Decode.float |> Decode.nullable)


intersTotal : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
intersTotal =
    Object.selectionForField "(Maybe Float)" "intersTotal" [] (Decode.float |> Decode.nullable)


interdTotal : SelectionSet (Maybe Float) BigStructure.Object.EvoEF2Results
interdTotal =
    Object.selectionForField "(Maybe Float)" "interdTotal" [] (Decode.float |> Decode.nullable)


stateId : SelectionSet (Maybe Int) BigStructure.Object.EvoEF2Results
stateId =
    Object.selectionForField "(Maybe Int)" "stateId" [] (Decode.int |> Decode.nullable)


state :
    SelectionSet decodesTo BigStructure.Object.State
    -> SelectionSet (Maybe decodesTo) BigStructure.Object.EvoEF2Results
state object____ =
    Object.selectionForCompositeField "state" [] object____ (identity >> Decode.nullable)
