-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module BigStructure.Object.State exposing (..)

import BigStructure.InputObject
import BigStructure.Interface
import BigStructure.Object
import BigStructure.Scalar
import BigStructure.ScalarCodecs
import BigStructure.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet BigStructure.ScalarCodecs.Id BigStructure.Object.State
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (BigStructure.ScalarCodecs.codecs |> BigStructure.Scalar.unwrapCodecs |> .codecId |> .decoder)


stateNumber : SelectionSet Int BigStructure.Object.State
stateNumber =
    Object.selectionForField "Int" "stateNumber" [] Decode.int


composition : SelectionSet String BigStructure.Object.State
composition =
    Object.selectionForField "String" "composition" [] Decode.string


torsionAngles : SelectionSet String BigStructure.Object.State
torsionAngles =
    Object.selectionForField "String" "torsionAngles" [] Decode.string


hydrophobicFitness : SelectionSet (Maybe Float) BigStructure.Object.State
hydrophobicFitness =
    Object.selectionForField "(Maybe Float)" "hydrophobicFitness" [] (Decode.float |> Decode.nullable)


isProteinOnly : SelectionSet Bool BigStructure.Object.State
isProteinOnly =
    Object.selectionForField "Bool" "isProteinOnly" [] Decode.bool


isoelectricPoint : SelectionSet Float BigStructure.Object.State
isoelectricPoint =
    Object.selectionForField "Float" "isoelectricPoint" [] Decode.float


numOfResidues : SelectionSet Int BigStructure.Object.State
numOfResidues =
    Object.selectionForField "Int" "numOfResidues" [] Decode.int


mass : SelectionSet Float BigStructure.Object.State
mass =
    Object.selectionForField "Float" "mass" [] Decode.float


meanPackingDensity : SelectionSet Float BigStructure.Object.State
meanPackingDensity =
    Object.selectionForField "Float" "meanPackingDensity" [] Decode.float


biolUnitId : SelectionSet (Maybe Int) BigStructure.Object.State
biolUnitId =
    Object.selectionForField "(Maybe Int)" "biolUnitId" [] (Decode.int |> Decode.nullable)


biolUnit :
    SelectionSet decodesTo BigStructure.Object.BiolUnit
    -> SelectionSet (Maybe decodesTo) BigStructure.Object.State
biolUnit object____ =
    Object.selectionForCompositeField "biolUnit" [] object____ (identity >> Decode.nullable)


budeffResults :
    SelectionSet decodesTo BigStructure.Object.BudeFFResults
    -> SelectionSet (Maybe decodesTo) BigStructure.Object.State
budeffResults object____ =
    Object.selectionForCompositeField "budeffResults" [] object____ (identity >> Decode.nullable)


evoef2Results :
    SelectionSet decodesTo BigStructure.Object.EvoEF2Results
    -> SelectionSet (Maybe decodesTo) BigStructure.Object.State
evoef2Results object____ =
    Object.selectionForCompositeField "evoef2Results" [] object____ (identity >> Decode.nullable)


dfire2Results :
    SelectionSet decodesTo BigStructure.Object.DFIRE2Results
    -> SelectionSet (Maybe decodesTo) BigStructure.Object.State
dfire2Results object____ =
    Object.selectionForCompositeField "dfire2Results" [] object____ (identity >> Decode.nullable)


rosettaResults :
    SelectionSet decodesTo BigStructure.Object.RosettaResults
    -> SelectionSet (Maybe decodesTo) BigStructure.Object.State
rosettaResults object____ =
    Object.selectionForCompositeField "rosettaResults" [] object____ (identity >> Decode.nullable)


aggrescan3dResults :
    SelectionSet decodesTo BigStructure.Object.Aggrescan3DResults
    -> SelectionSet (Maybe decodesTo) BigStructure.Object.State
aggrescan3dResults object____ =
    Object.selectionForCompositeField "aggrescan3dResults" [] object____ (identity >> Decode.nullable)


chains :
    SelectionSet decodesTo BigStructure.Object.Chain
    -> SelectionSet (Maybe (List (Maybe decodesTo))) BigStructure.Object.State
chains object____ =
    Object.selectionForCompositeField "chains" [] object____ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
