-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module BigStructure.Mutation exposing (..)

import BigStructure.InputObject
import BigStructure.Interface
import BigStructure.Object
import BigStructure.Scalar
import BigStructure.ScalarCodecs
import BigStructure.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreateDesignRequiredArguments =
    { pdbString : String
    , uuid : String
    }


createDesign : CreateDesignRequiredArguments -> SelectionSet decodesTo BigStructure.Object.CreateDesign -> SelectionSet decodesTo RootMutation
createDesign requiredArgs object_ =
    Object.selectionForCompositeField "createDesign" [ Argument.required "pdbString" requiredArgs.pdbString Encode.string, Argument.required "uuid" requiredArgs.uuid Encode.string ] object_ identity
