-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module BigStructure.Object exposing (..)


type Aggrescan3DResults
    = Aggrescan3DResults


type BiolUnit
    = BiolUnit


type BudeFFResults
    = BudeFFResults


type Chain
    = Chain


type DFIRE2Results
    = DFIRE2Results


type EvoEF2Results
    = EvoEF2Results


type Pdb
    = Pdb


type RosettaResults
    = RosettaResults


type State
    = State
