-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module BigStructure.ScalarCodecs exposing (..)

import BigStructure.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    BigStructure.Scalar.Id


codecs : BigStructure.Scalar.Codecs Id
codecs =
    BigStructure.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
